const DATA = [
  {
    idDrink: '17222',
    strDrink: 'A1',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Pour all ingredients into a cocktail shaker, mix and serve over ice into a chilled glass.',
    strInstructionsES:
      'Verter todos los ingredientes en una coctelera, mezclar y servir con hielo en una copa fría.',
    strInstructionsDE:
      'Alle Zutaten in einen Cocktailshaker geben, mischen und über Eis in ein gekühltes Glas servieren.',
    strInstructionsFR:
      'Verser tous les ingrédients dans un shaker, mélanger et servir avec des glaçons dans un verre réfrigéré.',
    strInstructionsIT:
      'Versare tutti gli ingredienti in uno shaker, mescolare e servire con ghiaccio in un bicchiere freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Grand Marnier',
    strIngredient3: 'Lemon Juice',
    strIngredient4: 'Grenadine',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 3/4 shot ',
    strMeasure2: '1 Shot ',
    strMeasure3: '1/4 Shot',
    strMeasure4: '1/8 Shot',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-07 21:42:09',
  },
  {
    idDrink: '17225',
    strDrink: 'Ace',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Martini Glass',
    strInstructions:
      'Shake all the ingredients in a cocktail shaker and ice then strain in a cold glass.',
    strInstructionsES:
      'Agitar todos los ingredientes en una coctelera con hielo y colar en un vaso frío.',
    strInstructionsDE:
      'Alle Zutaten in einem Cocktailshaker mit Eis schütteln und dann in einem kalten Glas abseihen.',
    strInstructionsFR:
      'Agiter tous les ingrédients dans un shaker avec de la glace, puis filtrer dans un verre froid.',
    strInstructionsIT:
      'Shakerare tutti gli ingredienti in uno shaker e ghiaccio, quindi filtrare in un bicchiere freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Grenadine',
    strIngredient3: 'Heavy cream',
    strIngredient4: 'Milk',
    strIngredient5: 'Egg White',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 shots ',
    strMeasure2: '1/2 shot ',
    strMeasure3: '1/2 shot ',
    strMeasure4: '1/2 shot',
    strMeasure5: '1/2 Fresh',
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-07 22:05:06',
  },
  {
    idDrink: '13501',
    strDrink: 'ABC',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Shot',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Shot glass',
    strInstructions: 'Layered in a shot glass.',
    strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
    strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Versa in ordine di lettera i vari ingredienti. 1/3 del bicchiere va riempito con l'Amaretto, 1/3 di Baileys e il restante di Cognac.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
    strIngredient1: 'Amaretto',
    strIngredient2: 'Baileys irish cream',
    strIngredient3: 'Cognac',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1/3 ',
    strMeasure2: '1/3 ',
    strMeasure3: '1/3 ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-08-31 19:32:08',
  },
  {
    idDrink: '14610',
    strDrink: 'ACID',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Shot',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Shot glass',
    strInstructions:
      'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
    strInstructionsES:
      'Vierta primero el Bacardi 151, seguido del Wild Turkey 101 y sirva con Coca-Cola o Dr Pepper.',
    strInstructionsDE:
      'Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.',
    strInstructionsFR: null,
    strInstructionsIT: 'Versa prima il Bacardi 151 seguito dal 101, servito con una Coca-Cola.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
    strIngredient1: '151 proof rum',
    strIngredient2: 'Wild Turkey',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 oz Bacardi ',
    strMeasure2: '1 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-11-15 11:28:37',
  },
  {
    idDrink: '17837',
    strDrink: 'Adam',
    strDrinkAlternate: null,
    strTags: 'Alcoholic,Holiday',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
    strInstructionsES:
      'En una coctelera llena hasta la mitad con cubitos de hielo, mezcle todos los ingredientes. Agitar bien. Colar en una copa de cóctel.',
    strInstructionsDE:
      'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
    strInstructionsFR:
      'Dans un shaker à moitié rempli de glaçons, mélanger tous les ingrédients. Bien agiter. Filtrer dans un verre à cocktail.',
    strInstructionsIT:
      'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/v0at4i1582478473.jpg',
    strIngredient1: 'Dark rum',
    strIngredient2: 'Lemon juice',
    strIngredient3: 'Grenadine',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 oz ',
    strMeasure2: '1 oz ',
    strMeasure3: '1 tsp ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'Yes',
    dateModified: '2016-09-02 11:29:29',
  },
  {
    idDrink: '13938',
    strDrink: 'AT&T',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball Glass',
    strInstructions: 'Pour Vodka and Gin over ice, add Tonic and Stir',
    strInstructionsES: 'Vierta el vodka y la ginebra sobre el hielo, añada la tónica y remueva',
    strInstructionsDE: 'Wodka und Gin über das Eis gießen, Tonic hinzufügen und umrühren.',
    strInstructionsFR: 'Verser la vodka et le gin sur de la glace, ajouter le Tonic et remuer.',
    strInstructionsIT:
      "Versare la vodka e il gin sul ghiaccio, aggiungere l'acqua tonica e mescolare",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rhhwmp1493067619.jpg',
    strIngredient1: 'Absolut Vodka',
    strIngredient2: 'Gin',
    strIngredient3: 'Tonic water',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 oz ',
    strMeasure2: '1 oz ',
    strMeasure3: '4 oz ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-04-24 22:00:19',
  },
  {
    idDrink: '17833',
    strDrink: 'A. J.',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions: 'Shake ingredients with ice, strain into a cocktail glass, and serve.',
    strInstructionsES: 'Agitar los ingredientes con hielo, colar en una copa de cóctel y servir.',
    strInstructionsDE: 'Zutaten mit Eis schütteln, in ein Cocktailglas abseihen und servieren.',
    strInstructionsFR:
      'Secouer les ingrédients avec de la glace, filtrer dans un verre à cocktail et servir.',
    strInstructionsIT:
      'Shakerare gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l74qo91582480316.jpg',
    strIngredient1: 'Applejack',
    strIngredient2: 'Grapefruit juice',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 oz ',
    strMeasure2: '1 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'Yes',
    dateModified: '2016-09-02 11:16:58',
  },
  {
    idDrink: '12764',
    strDrink: 'Karsk',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.',
    strInstructionsES:
      'Se pone una moneda de cobre en una taza de café y se llena con café hasta que ya no se vea la moneda, después se añade alcohol hasta que se vea la moneda. Especialidad noruega.',
    strInstructionsDE:
      'Legen Sie eine Kupfermünze in eine Kaffeetasse und füllen Sie sie mit Kaffee, bis Sie die Münze nicht mehr sehen, dann fügen Sie Alkohol hinzu, bis Sie die Münze wieder sehen. Norwegische Spezialität.',
    strInstructionsFR:
      "Mettez une pièce de monnaie en cuivre dans une tasse à café et remplissez-la de café jusqu'à ce que vous ne voyiez plus la pièce, puis ajoutez de l'alcool jusqu'à ce que vous voyiez la pièce. Spécialité norvégienne.",
    strInstructionsIT:
      "Metti una moneta di rame in una tazza da caffè e riempila di caffè finché non vedi più la moneta, quindi aggiungi l'alcol finché non vedi la moneta. Specialità norvegese.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg',
    strIngredient1: 'Coffee',
    strIngredient2: 'Grain alcohol',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 part ',
    strMeasure2: '2 parts ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-02-20 14:54:31',
  },
  {
    idDrink: '12776',
    strDrink: 'Melya',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Coffee / Tea',
    strIBA: null,
    strAlcoholic: 'Non alcoholic',
    strGlass: 'Coffee mug',
    strInstructions:
      'Brew espresso. In a coffee mug, place 1 teaspoon of unsweetened powdered cocoa, then cover a teaspoon with honey and drizzle it into the cup. Stir while the coffee brews, this is the fun part. The cocoa seems to coat the honey without mixing, so you get a dusty, sticky mass that looks as though it will never mix. Then all at once, presto! It looks like dark chocolate sauce. Pour hot espresso over the honey, stirring to dissolve. Serve with cream.',
    strInstructionsES:
      'Prepara café expreso. En una taza de café, coloca 1 cucharadita de cacao en polvo sin azúcar, luego cubre una cucharadita con miel y rocíala en la taza. Revuelve mientras se prepara el café, esta es la parte divertida. El cacao parece cubrir la miel sin mezclarse, por lo que se obtiene una masa polvorienta y pegajosa que parece que nunca se mezclará. Entonces, de repente, ¡listo! Parece salsa de chocolate amargo. Vierta el espresso caliente sobre la miel, revolviendo para que se disuelva. Servir con crema.',
    strInstructionsDE:
      'Espresso zubereiten. In eine Kaffeetasse 1 Teelöffel ungesüßten, pulverisierten Kakao geben, dann einen Teelöffel Honig in die Tasse träufeln. Rühren Sie um, während der Kaffee brüht, das ist der lustige Teil. Der Kakao scheint den Honig ohne Mischen zu überziehen, so dass Sie eine dichte, klebrige Masse erhalten, die aussieht, als würde sie sich nie vermischen. Dann auf einmal, presto! Es sieht aus wie dunkle Schokoladensoße. Heißen Espresso über den Honig gießen und unter Rühren auflösen. Mit Sahne servieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      "Prepara l'espresso.\r\nIn una tazza da caffè, mettete 1 cucchiaino di cacao amaro in polvere, quindi coprite un cucchiaino con del miele e versatelo nella tazza.\r\nMescola mentre il caffè si prepara, questa è la parte divertente.\r\nIl cacao sembra ricoprire il miele senza mescolarsi, quindi si ottiene una massa polverosa e appiccicosa che sembra non si mescolerà mai.\r\nVersare l'espresso caldo sul miele, mescolando per scioglierlo.\r\nServire con la panna.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xwtptq1441247579.jpg',
    strIngredient1: 'Espresso',
    strIngredient2: 'Honey',
    strIngredient3: 'Cocoa powder',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: null,
    strMeasure2: 'Unsweetened ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2015-09-03 03:32:59',
  },
  {
    idDrink: '17185',
    strDrink: 'Casino',
    strDrinkAlternate: null,
    strTags: 'IBA',
    strVideo: 'https://www.youtube.com/watch?v=C6v8NsaDNj8',
    strCategory: 'Ordinary Drink',
    strIBA: 'Unforgettables',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Pour all ingredients into shaker with ice cubes. Shake well. Strain into chilled cocktail glass. Garnish with a lemon twist and a maraschino cherry. Serve without a straw.',
    strInstructionsES:
      'Vierta todos los ingredientes en una coctelera con cubitos de hielo. Agitar bien. Colar en una copa de cóctel fría. Decorar con un twist de limón y una cereza al marrasquino. Servir sin pajita.',
    strInstructionsDE:
      'Alle Zutaten in den Shaker mit Eiswürfeln geben. Gut schütteln. In ein gekühltes Cocktailglas abseihen. Mit einer Zitronenscheibe und einer Maraschinokirsche garnieren. Ohne Strohhalm servieren.',
    strInstructionsFR:
      "Verser tous les ingrédients dans un shaker avec des glaçons. Bien agiter. Filtrer dans un verre à cocktail réfrigéré. Décorer d'un zeste de citron et d'une cerise au marasquin. Servir sans paille.",
    strInstructionsIT:
      'Versare tutti gli ingredienti in uno shaker con cubetti di ghiaccio.\r\nAgitare bene.\r\nFiltrare in una coppetta da cocktail ghiacciata.\r\nGuarnire con una scorza di limone e una ciliegia al maraschino.\r\nServire senza cannuccia.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/1mvjxg1504348579.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Maraschino liqueur',
    strIngredient3: 'Lemon juice',
    strIngredient4: 'Orange bitters',
    strIngredient5: 'Cherry',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 oz ',
    strMeasure2: '1/4 tsp ',
    strMeasure3: '1/4 tsp ',
    strMeasure4: '2 dashes ',
    strMeasure5: '1 ',
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 11:36:19',
  },
  {
    idDrink: '17839',
    strDrink: 'Affair',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Pour schnapps, orange juice, and cranberry juice over ice in a highball glass. Top with club soda and serve.',
    strInstructionsES:
      'Vierta el aguardiente, el zumo de naranja y el zumo de arándanos sobre hielo en un vaso alto. Añadir club soda y servir.',
    strInstructionsDE:
      'Gießen Sie Schnaps, Orangensaft und Cranberrysaft über Eis in ein Highball-Glas. Mit Club-Soda überziehen und servieren.',
    strInstructionsFR:
      "Verser le schnaps, le jus d'orange et le jus de canneberge sur de la glace dans un verre highball. Compléter avec du club soda et servir.",
    strInstructionsIT:
      "Versare la grappa, il succo d'arancia e il succo di mirtillo rosso sul ghiaccio in un bicchiere highball. Completare con la soda club e servire.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/h5za6y1582477994.jpg',
    strIngredient1: 'Strawberry schnapps',
    strIngredient2: 'Orange juice',
    strIngredient3: 'Cranberry juice',
    strIngredient4: 'Club soda',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 oz ',
    strMeasure2: '2 oz ',
    strMeasure3: '2 oz ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'Yes',
    dateModified: '2016-09-01 10:05:34',
  },
  {
    idDrink: '16031',
    strDrink: 'Radler',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions: 'Pour beer into large mug, slowly add the 7-up (or Sprite).',
    strInstructionsES:
      'Vierte la cerveza en una jarra grande y añade lentamente la 7-up (o Sprite).',
    strInstructionsDE:
      'Bier in einen großen Becher gießen, langsam den 7-up (oder Sprite) hinzufügen.',
    strInstructionsFR:
      'Verser la bière dans une grande chope et ajouter lentement le 7-up (ou le Sprite).',
    strInstructionsIT:
      'Versare la birra in una tazza grande, aggiungere lentamente il 7up (o Sprite).',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xz8igv1504888995.jpg',
    strIngredient1: 'Beer',
    strIngredient2: '7-Up',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '12 oz ',
    strMeasure2: '12 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-08 17:43:15',
  },
  {
    idDrink: '17253',
    strDrink: 'Paloma',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Collins glass',
    strInstructions: 'Stir together and serve over ice.',
    strInstructionsES: 'Remover y servir con hielo.',
    strInstructionsDE: 'Zusammenrühren und über Eis servieren.',
    strInstructionsFR: 'Mélanger et servir sur des glaçons.',
    strInstructionsIT: 'Mescolate e servite con ghiaccio.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/samm5j1513706393.jpg',
    strIngredient1: 'Grape Soda',
    strIngredient2: 'Tequila',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '3 oz',
    strMeasure2: '1 1/2 oz',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-12-19 17:59:53',
  },
  {
    idDrink: '11149',
    strDrink: 'Boxcar',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Whiskey sour glass',
    strInstructions:
      'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.',
    strInstructionsES:
      'En una coctelera llena hasta la mitad con cubitos de hielo, mezcle todos los ingredientes. Agitar bien. Colar en un vaso sour.',
    strInstructionsDE:
      'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Sour Glas abseihen.',
    strInstructionsFR:
      'Dans un shaker à moitié rempli de glaçons, mélanger tous les ingrédients. Bien agiter. Filtrer dans un verre aigre.',
    strInstructionsIT:
      'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Filtrare in un bicchiere sour.Agitare bene.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/pwgtpa1504366376.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Triple sec',
    strIngredient3: 'Lemon juice',
    strIngredient4: 'Grenadine',
    strIngredient5: 'Egg white',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 oz ',
    strMeasure2: '1 oz ',
    strMeasure3: '1 tsp ',
    strMeasure4: '1/2 tsp ',
    strMeasure5: '1 ',
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 16:32:57',
  },
  {
    idDrink: '17205',
    strDrink: 'Mimosa',
    strDrinkAlternate: null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: 'Contemporary Classics',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Champagne flute',
    strInstructions:
      'Ensure both ingredients are well chilled, then mix into the glass. Serve cold.',
    strInstructionsES: null,
    strInstructionsDE:
      'Achten Sie darauf, dass beide Zutaten gut gekühlt sind, und mischen Sie sie dann in das Glas. Kalt servieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Assicurati che entrambi gli ingredienti siano ben raffreddati, quindi mescolali nel bicchiere.\r\nServire freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/juhcuu1504370685.jpg',
    strIngredient1: 'Champagne',
    strIngredient2: 'Orange juice',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: 'Chilled ',
    strMeasure2: '2 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 17:44:45',
  },
  {
    idDrink: '15266',
    strDrink: 'Avalon',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Fill a tall glass with ice. Layer the Finlandia Vodka, lemon and apple juices, Pisang Ambon, and top up with lemonade. Stir slightly and garnish with a spiralled cucumber skin and a red cherry. The cucumber provides zest and looks attractive. This drink, created by Timo Haimi, took first prize in the 1991 Finlandia Vodka Long Drink Competition.',
    strInstructionsES:
      'Llene un vaso alto con hielo. Añadir el Finlandia Vodka, los zumos de limón y manzana, el Pisang Ambon y completar con limonada. Remover ligeramente y decorar con una piel de pepino en espiral y una cereza roja. El pepino aporta sabor y un aspecto atractivo. Esta bebida, creada por Timo Haimi, obtuvo el primer premio en el Concurso de Tragos Largos con Vodka Finlandia de 1991.',
    strInstructionsDE:
      'Füllen Sie ein hohes Glas mit Eis. Legen Sie den Finlandia Wodka, Zitronen- und Apfelsäfte, Pisang Ambon und geben Sie Limonade dazu. Leicht umrühren und mit einer spiralförmigen Gurkenhaut und einer roten Kirsche garnieren. Die Gurke sorgt für Schärfe und sieht attraktiv aus. Dieses von Timo Haimi kreierte Getränk erhielt 1991 den ersten Preis beim Finlandia Wodka Long Drink Wettbewerb.',
    strInstructionsFR:
      "Remplir un grand verre de glace. Superposer la vodka Finlandia, les jus de citron et de pomme, le Pisang Ambon et compléter avec de la limonade. Remuer légèrement et décorer d'une spirale de concombre et d'une cerise rouge. Le concombre apporte du piquant et est très esthétique. Cette boisson, créée par Timo Haimi, a remporté le premier prix du concours de Long Drink de Finlandia Vodka en 1991.",
    strInstructionsIT:
      'Riempi un bicchiere alto di ghiaccio.\r\nVersare la Vodka, succhi di limone, mela, Pisang Ambon o un liquore alla banana e completare con la limonata.\r\nMescolare leggermente e guarnire con una buccia di cetriolo a spirale e una ciliegia rossa.\r\nIl cetriolo fornisce la scorza e sembra attraente.\r\nQuesta bevanda, creata da Timo Haimi, ha vinto il primo premio nel 1991 Finlandia Vodka Long Drink Competition.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/3k9qic1493068931.jpg',
    strIngredient1: 'Vodka',
    strIngredient2: 'Pisang Ambon',
    strIngredient3: 'Apple juice',
    strIngredient4: 'Lemon juice',
    strIngredient5: 'Lemonade',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '3 parts',
    strMeasure2: '1 part ',
    strMeasure3: '6 parts ',
    strMeasure4: '1 1/2 part ',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-04-24 22:22:11',
  },
  {
    idDrink: '15106',
    strDrink: 'Apello',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Other / Unknown',
    strIBA: null,
    strAlcoholic: 'Non alcoholic',
    strGlass: 'Collins Glass',
    strInstructions: 'Stirr. Grnish with maraschino cherry.',
    strInstructionsES: 'Revuelva. Grnish con cereza al marrasquino.',
    strInstructionsDE: 'Rühren. Mit Maraschinokirsche garnieren.',
    strInstructionsFR: 'Remuer. Garnir de cerises au marasquin.',
    strInstructionsIT:
      'Versare tutti gli ingredienti in un mixing glass. Mescolate.\r\nGuarnire con una ciliegia al maraschino.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/uptxtv1468876415.jpg',
    strIngredient1: 'Orange juice',
    strIngredient2: 'Grapefruit juice',
    strIngredient3: 'Apple juice',
    strIngredient4: 'Maraschino cherry',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '4 cl ',
    strMeasure2: '3 cl ',
    strMeasure3: '1 cl ',
    strMeasure4: '1 ',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-07-18 22:13:35',
  },
  {
    idDrink: '11872',
    strDrink: 'Orgasm',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.',
    strInstructionsES:
      'Agite todos los ingredientes con hielo, cuele en una copa de cóctel fría y sirva.',
    strInstructionsDE:
      'Alle Zutaten mit Eis schütteln, in ein gekühltes Cocktailglas abseihen und servieren.',
    strInstructionsFR:
      'Secouez tous les ingrédients avec de la glace, filtrez dans un verre à cocktail réfrigéré et servez.',
    strInstructionsIT:
      'Shakerare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail fredda e servire.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vr6kle1504886114.jpg',
    strIngredient1: 'Creme de Cacao',
    strIngredient2: 'Amaretto',
    strIngredient3: 'Triple sec',
    strIngredient4: 'Vodka',
    strIngredient5: 'Light cream',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1/2 oz white ',
    strMeasure2: '1/2 oz ',
    strMeasure3: '1/2 oz ',
    strMeasure4: '1/2 oz ',
    strMeasure5: '1 oz ',
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-08 16:55:14',
  },
  {
    idDrink: '17176',
    strDrink: 'Ipamena',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Non alcoholic',
    strGlass: 'Wine Glass',
    strInstructions:
      'Cut half a lime into pieces, place in a shaker, add the sugar and crush. Measure the passion fruit juice, add it to the shaker and fill up with ice cubes. Close the shaker and shake vigorously. Pour the liquid into a glass, top up with ginger ale, stir with a teaspoon and then garnish the rim of the glass with a slice of lime',
    strInstructionsES: null,
    strInstructionsDE:
      'Eine halbe Limette in Stücke schneiden, in einen Shaker geben, Zucker hinzufügen und zerdrücken. Passionsfruchtsaft abmessen, in den Shaker geben und mit Eiswürfeln auffüllen. Schließen Sie den Shaker und schütteln Sie ihn kräftig. Die Flüssigkeit in ein Glas gießen, mit Ginger Ale auffüllen, mit einem Teelöffel umrühren und dann den Rand des Glases mit einer Scheibe Limette garnieren.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Tagliare a pezzi mezzo lime, metterlo in uno shaker, aggiungere lo zucchero e schiacciare.\r\nMisurate il succo di frutto della passione, aggiungetelo allo shaker e riempitelo con cubetti di ghiaccio.\r\nChiudi lo shaker e agita energicamente.\r\nVersare il liquido in un bicchiere, rabboccare con ginger ale, mescolare con un cucchiaino e poi guarnire il bordo del bicchiere con una fetta di lime',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yswuwp1469090992.jpg',
    strIngredient1: 'Lime',
    strIngredient2: 'Brown sugar',
    strIngredient3: 'Passion fruit juice',
    strIngredient4: 'Ginger ale',
    strIngredient5: 'Ice',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '½',
    strMeasure2: '2 tsp',
    strMeasure3: '4 cl',
    strMeasure4: 'top up with',
    strMeasure5: 'fill',
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-07-21 09:49:52',
  },
  {
    idDrink: '15933',
    strDrink: 'Zambeer',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Soft Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Collins Glass',
    strInstructions: 'Mix sambuca with rootbeer and stir. Add ice',
    strInstructionsES: null,
    strInstructionsDE: 'Sambuca mit Root Bier mischen und umrühren. Füge Eis hinzu.',
    strInstructionsFR: null,
    strInstructionsIT:
      'Mescolare la sambuca con la birra alla radice e mescolare. Aggiungi il ghiaccio',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/bje5401485619578.jpg',
    strIngredient1: 'Sambuca',
    strIngredient2: 'Root beer',
    strIngredient3: 'Ice',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 oz ',
    strMeasure2: 'Add 10 oz ',
    strMeasure3: 'cubes',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-01-28 16:06:18',
  },
  {
    idDrink: '17210',
    strDrink: 'Bramble',
    strDrinkAlternate: null,
    strTags: 'IBA,NewEra',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: 'New Era Drinks',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Old-Fashioned glass',
    strInstructions:
      'Fill glass with crushed ice. Build gin, lemon juice and simple syrup over. Stir, and then pour blackberry liqueur over in a circular fashion to create marbling effect. Garnish with two blackberries and lemon slice.',
    strInstructionsES:
      'Llenar el vaso con hielo picado. Echar por encima la ginebra, el zumo de limón y el sirope simple. Remover y, a continuación, verter el licor de mora en forma circular para crear un efecto marmolado. Decorar con dos moras y una rodaja de limón.',
    strInstructionsDE:
      'Füllen Sie das Glas mit zerstoßenem Eis. Den Gin, den Zitronensaft und den Sirup dazugeben. Rühren Sie um und gießen Sie dann Brombeerlikör kreisförmig darüber, um einen Marmoriereffekt zu erzielen. Mit zwei Brombeeren und einer Zitronenscheibe garnieren.',
    strInstructionsFR:
      'Remplir le verre de glace pilée. Verser le gin, le jus de citron et le sirop simple. Remuer, puis verser la liqueur de mûre de façon circulaire pour créer un effet de marbrure. Décorer avec deux mûres et une tranche de citron.',
    strInstructionsIT:
      'Riempi il bicchiere con ghiaccio tritato.\r\nAggiungi gin, succo di limone e sciroppo semplice.\r\nMescolare e poi versare il liquore alla mora in modo circolare per creare un effetto marmorizzato.\r\nGuarnire con due more e una fetta di limone.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/twtbh51630406392.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'lemon juice',
    strIngredient3: 'Sugar syrup',
    strIngredient4: 'Creme de Mure',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '4 cl',
    strMeasure2: '1.5 cl',
    strMeasure3: '1 cl',
    strMeasure4: '1.5 cl',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: 'https://www.instagram.com/p/CSR2YF3M9uT',
    strImageAttribution: '@wanderingdane',
    strCreativeCommonsConfirmed: 'Yes',
    dateModified: '2017-09-02 18:15:26',
  },
  {
    idDrink: '12127',
    strDrink: 'Sazerac',
    strDrinkAlternate: null,
    strTags: 'IBA,Classic',
    strVideo: 'https://www.youtube.com/watch?v=RuZzOcjJUYw',
    strCategory: 'Ordinary Drink',
    strIBA: 'Unforgettables',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Old-fashioned glass',
    strInstructions:
      'Rinse a chilled old-fashioned glass with the absinthe, add crushed ice, and set it aside. Stir the remaining ingredients over ice and set it aside. Discard the ice and any excess absinthe from the prepared glass, and strain the drink into the glass. Add the lemon peel for garnish.',
    strInstructionsES:
      'Enjuaga un vaso old-fashioned frío con la absenta, añade hielo picado y resérvalo. Remover el resto de ingredientes con hielo y reservar. Deseche el hielo y el exceso de absenta del vaso preparado y cuele la bebida en el vaso. Añada la piel de limón para adornar.',
    strInstructionsDE:
      'Ein gekühltes old-fashioned Glas mit dem Absinth ausspülen, zerstoßenes Eis hinzufügen und beiseite stellen. Die restlichen Zutaten über das Eis geben und beiseite stellen. Entsorgen Sie das Eis und den überschüssigen Absinth aus dem vorbereiteten Glas und seihen Sie das Getränk in das Glas. Die Zitronenschale als Garnierung hinzufügen.',
    strInstructionsFR:
      "Rincer un verre old-fashioned bien frais avec l'absinthe, ajouter de la glace pilée et réserver. Mélangez les autres ingrédients avec de la glace et mettez-les de côté. Jeter la glace et l'excès d'absinthe dans le verre préparé et filtrer la boisson dans le verre. Ajouter le zeste de citron pour la décoration.",
    strInstructionsIT:
      "Sciacquare un bicchiere vecchio stile freddo con l'assenzio, aggiungere il ghiaccio tritato e metterlo da parte. Mescola gli ingredienti rimanenti sul ghiaccio e mettilo da parte. Togli il ghiaccio e l'assenzio in eccesso dal bicchiere precedentemente preparato e filtra la bevanda nel bicchiere .Aggiungere la scorza di limone per guarnire.",
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vvpxwy1439907208.jpg',
    strIngredient1: 'Ricard',
    strIngredient2: 'Sugar',
    strIngredient3: 'Peychaud bitters',
    strIngredient4: 'Water',
    strIngredient5: 'Bourbon',
    strIngredient6: 'Lemon peel',
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 tsp ',
    strMeasure2: '1/2 tsp superfine ',
    strMeasure3: '2 dashes ',
    strMeasure4: '1 tsp ',
    strMeasure5: '2 oz ',
    strMeasure6: '1 twist of ',
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2015-08-18 15:13:28',
  },
  {
    idDrink: '11023',
    strDrink: 'Almeria',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      'In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.',
    strInstructionsES:
      'En una coctelera llena hasta la mitad con cubitos de hielo, mezcle todos los ingredientes. Agitar bien. Colar en una copa de cóctel.',
    strInstructionsDE:
      'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, alle Zutaten vermengen. Gut schütteln. In ein Cocktailglas abseihen.',
    strInstructionsFR:
      'Dans un shaker à moitié rempli de glaçons, mélanger tous les ingrédients. Bien agiter. Filtrer dans un verre à cocktail.',
    strInstructionsIT:
      'In uno shaker riempito a metà con cubetti di ghiaccio, unire tutti gli ingredienti.Agitare bene.Filtrare in un bicchiere da cocktail.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/rwsyyu1483388181.jpg',
    strIngredient1: 'Dark rum',
    strIngredient2: 'Kahlua',
    strIngredient3: 'Egg white',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 oz ',
    strMeasure2: '1 oz ',
    strMeasure3: '1 ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-01-02 20:16:21',
  },
  {
    idDrink: '17228',
    strDrink: 'Addison',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Martini Glass',
    strInstructions: 'Shake together all the ingredients and strain into a cold glass.',
    strInstructionsES: 'Agite todos los ingredientes y cuélelos en un vaso frío.',
    strInstructionsDE: 'Alle Zutaten vermengen und in ein kaltes Glas abseihen.',
    strInstructionsFR: 'Secouer tous les ingrédients et filtrer dans un verre froid.',
    strInstructionsIT: 'Shakerare insieme tutti gli ingredienti e filtrare in un bicchiere freddo.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yzva7x1504820300.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Vermouth',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 1/2 shot ',
    strMeasure2: '1 1/2 shot ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-07 22:38:20',
  },
  {
    idDrink: '17217',
    strDrink: 'Vampiro',
    strDrinkAlternate: null,
    strTags: 'IBA,NewEra',
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: 'New Era Drinks',
    strAlcoholic: 'Alcoholic',
    strGlass: 'Old-Fashioned glass',
    strInstructions:
      'Vampiros may be made in a tall glass or an old fashioned glass. Bartenders may first "rim" the glass with Kosher Salt, which is done by placing a layer of Kosher Salt on a chopping board, moistening the glass\' rim with lime juice or water, and then placing the upside down glass rim onto the Kosher Salt, so that the salt sticks to the moistened rim. The second step is to fill half the glass with ice and add one or two shooter glasses full of high quality Tequila. The next stage is to add the flavouring elements. This is done by squeezing a fresh lime into the glass, adding a few grains of salt, adding citrus-flavoured soda pop, until the glass is 4/5 full, and then adding spicy Viuda de Sanchez (or orange juice, lime juice and pico de gallo). The final step is to stir the ingredients so that the flavours are properly blended.',
    strInstructionsES:
      'Los vampiros pueden prepararse en un vaso alto o en un vaso old fashioned. En primer lugar, los camareros pueden "poner el borde" del vaso con sal Kosher, lo que se hace colocando una capa de sal Kosher sobre una tabla de cortar, humedeciendo el borde del vaso con zumo de lima o agua y colocando el borde del vaso boca abajo sobre la sal Kosher, de modo que la sal se pegue al borde humedecido. El segundo paso es llenar la mitad del vaso con hielo y añadir uno o dos vasos llenos de tequila de alta calidad. El siguiente paso es añadir los elementos aromatizantes. Para ello, se exprime una lima fresca en el vaso, se añaden unos granos de sal, se añade gaseosa con sabor a cítricos hasta que el vaso esté 4/5 lleno y, a continuación, se añade Viuda de Sánchez picante (o zumo de naranja, zumo de lima y pico de gallo). El último paso es remover los ingredientes para que se mezclen bien los sabores.',
    strInstructionsDE:
      'Vampiros können in einem hohen Glas oder einem old fashioned Glas zubereitet werden. Der Barkeeper kann das Glas zuerst mit Koscher-Salz "umsäumen", indem er eine Schicht Koscher-Salz auf ein Schneidebrett legt, den Glasrand mit Limettensaft oder Wasser anfeuchtet und dann den umgedrehten Glasrand auf das Koscher-Salz legt, so dass das Salz am angefeuchteten Rand haftet. Der zweite Schritt ist, das halbe Glas mit Eis zu füllen und ein oder zwei Schaugläser mit hochwertigem Tequila hinzuzufügen. Im nächsten Schritt werden die Aromastoffe hinzugefügt. Dazu wird eine frische Limette in das Glas gepresst, einige Salzkörner hinzugefügt, zitrusartiges Natron, bis das Glas 4/5 voll ist, und dann würziges Viuda de Sanchez (oder Orangensaft, Limettensaft und pico de gallo) hinzugefügt. Der letzte Schritt ist, die Zutaten so zu rühren, dass die Aromen richtig vermischt werden.',
    strInstructionsFR:
      "Les Vampiros peuvent être servis dans un grand verre ou dans un verre à l'ancienne. Les barmen peuvent d'abord \"border\" le verre avec du sel casher, en plaçant une couche de sel casher sur une planche à découper, en humidifiant le bord du verre avec du jus de citron vert ou de l'eau, puis en plaçant le bord du verre renversé sur le sel casher, de sorte que le sel adhère au bord humidifié. La deuxième étape consiste à remplir la moitié du verre avec de la glace et à ajouter un ou deux verres à shooter remplis de Tequila de haute qualité. L'étape suivante consiste à ajouter les éléments aromatiques. Pour ce faire, pressez un citron vert frais dans le verre, ajoutez quelques grains de sel, ajoutez du soda aromatisé aux agrumes, jusqu'à ce que le verre soit rempli aux 4/5, puis ajoutez de la Viuda de Sanchez épicée (ou du jus d'orange, du jus de citron vert et du pico de gallo). La dernière étape consiste à remuer les ingrédients pour que les saveurs se mélangent bien.",
    strInstructionsIT:
      'I vampiri possono essere realizzati in un bicchiere alto o in un bicchiere vecchio stile.\r\nI baristi possono prima "bordare" il bicchiere con il sale Kosher, che viene fatto mettendo uno strato di sale Kosher su un tagliere, inumidendo il bordo del bicchiere con succo di lime o acqua, quindi posizionando il bordo del vetro capovolto sul Kosher Sale, in modo che il sale si attacchi al bordo inumidito.\r\nIl secondo passo è riempire metà del bicchiere di ghiaccio e aggiungere uno o due bicchieri da shot pieni di Tequila di alta qualità.\r\nLa fase successiva consiste nell\'aggiungere gli elementi aromatizzanti.\r\nQuesto viene fatto spremendo un lime fresco nel bicchiere, aggiungendo qualche granello di sale, aggiungendo soda pop aromatizzata agli agrumi, fino a quando il bicchiere non è pieno per 4/5, quindi aggiungere succo d\'arancia/succo di lime.\r\nIl passaggio finale è mescolare gli ingredienti in modo che i sapori siano ben amalgamati.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yfhn371504374246.jpg',
    strIngredient1: 'Tequila',
    strIngredient2: 'Tomato Juice',
    strIngredient3: 'Orange Juice',
    strIngredient4: 'Lime Juice',
    strIngredient5: 'Sugar Syrup',
    strIngredient6: 'Salt',
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '6 cl',
    strMeasure2: '3 cl',
    strMeasure3: '3 cl',
    strMeasure4: '1.5 cl',
    strMeasure5: '1 dash',
    strMeasure6: '1 pinch',
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 18:44:06',
  },
];